### PR TITLE
Update locale rules

### PR DESCRIPTION
**Pull request by danielhollas**
Issue: https://khanacademy.atlassian.net/browse/IC-773

Test plan:
 - npm run lint && npm run build && npm run test

Same as #46, but PR opened from a forked repo where I have write access.

### CODE REVIEW

**Comment by danielhollas** [comment]
Updated PR with recent Vietnamese updates as discussed on the forum.

https://international-forum.khanacademy.org/t/radio-tag-translation/3972/5

This is ready for deploy. For Vietnamese, it seems that autotranslation system will need to be patched as a separate task, see the forum post. Once this is deployed, the KhanAcademyDots plugin should be updated as well.

cc @mpolyak

**Comment by danielhollas** [comment]
Added Slovak rules per their team request.

**Review by mpolyak — APPROVED** [review]
Thanks!

**Review by justinmayhew — APPROVED** [review]
Thanks Daniel!

**Pull request merged**
