### PR TITLE
FIX: Repeating dec. dot notation with a period > 2 digits

### PR DESCRIPTION
**Pull request by danielhollas**
**Summary**
I misunderstood how the dot notation for repeating decimals works.
This PR fixes a case of repeating decimals
with a period that is longer than two digits.
Incidentally, this made the code simpler. :-)

For example:
1 / 7 = 0.\overline{142857} -> 1.\dot{1}4285\dot{7}

I also alphabetically sorted all locale arrays
and added few locales based on the latest input from Advocates.

Issue: https://khanacademy.atlassian.net/browse/CP-3984

**Test Plan:**
 - Open this exercise for Hungarian and verify that
   repeating decimals are translated correctly.
https://www.khanacademy.org/translations/edit/hu/e/converting_fractions_to_decimals/tree/upstream/by-pattern

 - Specifically, this string
   https://crowdin.com/translate/khanacademy/26308/enus-hu#5315597
   should be autotranslated as:
   '$4{,}1\\dot{6}6\dot{7}$'

### CODE REVIEW

**Comment by mpolyak** [comment]
@danielhollas is this still a draft, or is it ready to review?

**Comment by danielhollas** [comment]
@mpolyak it's ready for review, but I want to hold off merging, because I hope more Advocates will get back to me with their Math notations.

**Comment by danielhollas** [comment]
This can now be merged. Deploy to webapp should wait for the other PRs.

**Comment by mpolyak** [comment]
Hi @danielhollas, can I merge this one as well?

**Comment by danielhollas** [comment]
@mpolyak yep, full speed ahead. :-)

**Comment by danielhollas** [comment]
@mpolyak minor thing, but it would probably make sense to make the Github CI tests required to pass for the PR to be mergeable. This can be done in Settings->Branches by adding a branch protection rule for `master`.

**Pull request merged**
