### PR TITLE
Fix regexes in translateMath.

### PR DESCRIPTION
**Pull request by danielhollas**
Summary:
Well, this is embarassing...This commit fixes
1. regex for decimal point
2. regex for multiplication sign
This fixes issue #9

Test plan:
 - Run `npm run build && npm run test`
 - Fix manticore not passing proper locale to Translation Assistant
 - Carry on with test plan in previous commit.

### CODE REVIEW

**Comment by danielhollas** [comment]
@mpolyak the unescaped dot in regex for decimal comma was causing the problems in #9.

Also, `\\mult` is not a command. :sweat: For some reason, I have made this mistake over and over...

**Comment by mpolyak** [comment]
@danielhollas I confirmed that the following works:

```
    it('does offer translations', function() {
        const allItems = [{
            englishStr: 'The answers:\n\n$50 \\div 10=5$\n\n$50 \\times 10=500$',
            translatedStr: 'The answers:\n\n$50 \\mathbin{:} 10=5$\n\n$50 \\cdot 10=500$',
        }];
        const itemsToTranslate = [{
            englishStr: 'The answers:\n\n$460 \\div 10=46$\n\n$460 \\times 10=4600$',
            translatedStr: '',
        }];
        const translatedStrs = ['The answers:\n\n$460 \\mathbin{:} 10=46$\n\n$460 \\cdot 10=4600$'];

        assertSuggestions(allItems, itemsToTranslate, translatedStrs);
    });
```

However I still don't see translation suggestions. Should we try translating the example string in https://www.khanacademy.org/translations/edit/cs/e/multiplying-and-dividing-by-10/by-pattern so that I can check whether it will then offer a suggestion?

**Comment by danielhollas** [comment]
Wait, I don't understand. What do you mean you don't see translation suggestions? I am not sure what you are suggesting that I should do (add more tests?)

**Comment by mpolyak** [comment]
@danielhollas it's grouping by pattern but since the pattern has no translations, the `Add smart translations` button is disabled. I was wondering whether we should translate one string in the pattern to check whether it will enable adding smart translations to the rest of the pattern?

screen shot 2018-07-24 at 4 56 32 pm

**Comment by danielhollas** [comment]
I have made one translation, but feel free to experiment as you wish (I am assuming you have dev version of Manticore and can translate czech strings...)

**Comment by mpolyak** [comment]
Looks like it's working, `Add smart translations` button is now enabled for pattern.

screen shot 2018-07-24 at 5 20 43 pm

**Comment by mpolyak** [comment]
screen shot 2018-07-24 at 5 42 06 pm

Looks like it's working!

(I reverted the smart translations, so that it can be tested during deploy)

**Pull request merged**
