### PR TITLE
WIP: angle notations

### PR DESCRIPTION
**Pull request by danielhollas**

### CODE REVIEW

**Comment by danielhollas** [comment]
@mpolyak could you please take a look and deploy to ZND? I'd like to test this a bit more.

**Comment by mpolyak** [comment]
@danielhollas: https://prod-znd-200826-michaelp-3.khanacademy.org/

**Comment by danielhollas** [comment]
@mpolyak I apologize, but it seems the ZND deploy no longer works, I'm getting Internal Server Error:

```js
Internal Server Error

Error: Network error: /api/internal/graphql/footerDomainsQuery?fastly_cacheable=persist_until_publish&hash=646910179&variables=%7B%22curriculum%22%3A%22%22%7D&lang=en: Internal Server Error https://prod-znd-200826-michaelp-3.khanacademy.org/api/internal/graphql/footerDomainsQuery?fastly_cacheable=persist_until_publish&hash=646910179&variables=%7B%22curriculum%22%3A%22%22%7D&lang=en

Additional debug information

URL: https://prod-znd-200826-michaelp-3.khanacademy.org/

Headers:

{
    "host": "znd-200826-michaelp-3-dot-khan-academy.appspot.com",
    "x-forwarded-for": "89.24.37.40,185.31.18.35, 169.254.1.1",
    "x-forwarded-host": "prod-znd-200826-michaelp-3.khanacademy.org",
    "x-forwarded-proto": "https",
    "forwarded": "for=\"185.31.18.35\";proto=https",
    "user-agent": "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:81.0) Gecko/20100101 Firefox/81.0",
    "accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8",
    "accept-language": "cs,sk;q=0.8,en-US;q=0.5,en;q=0.3",
    "dnt": "1",
    "upgrade-insecure-requests": "1",
    "fastly-ssl": "1",
    "fastly-client-ip": "89.24.37.40",
    "x-forwarded-server": "cache-fra19135-FRA",
    "fastly-orig-accept-encoding": "gzip, deflate, br",
    "x-timer": "S1601716970.650947,VS0",
    "fastly-soc-x-request-id": "f45ea098bf3dfe2a18fa4197b946933a0742fbb67a5d009ef7cbc7a2f236a029",
    "x-fastly-tls": "1",
    "x-ka-use-render-gateway": "true",
    "x-fastly-country": "CZ",
    "x-fastly-region": "42",
    "x-ka-curriculum": "",
    "x-ka-orig-url": "/",
    "x-ka-orig-host": "prod-znd-200826-michaelp-3.khanacademy.org",
    "x-ka-is-e2e": "false",
    "x-ka-is-bot": "false",
    "x-ka-is-ios": "false",
    "x-ka-is-phone": "false",
    "x-ka-is-tablet": "false",
    "x-ka-is-unsupported-browser": "false",
    "x-ka-browser": "Firefox",
    "x-ka-browser-os": "Linux",
    "x-ka-lang": "en",
    "x-ka-locale": "en",
    "x-ka-bingo-id": "kaid_4509158585312999145869712",
    "x-ka-proxy-renew-kaal": "0",
    "x-ka-published-content-version": "080bcfe1c35b56c4052b033d400498b803cf5257",
    "x-ka-tmp-version-from-hostname": "znd-200826-michaelp-3",
    "x-ka-static-version": "201002-0714-7656ec5bbd6c",
    "x-varnish": "1725339217",
    "fastly-ff": "ltsxTZVz3/qY+PjkowxBUBQDaDchBm1aPceAyytMsr4=!FRA!cache-fra19135-FRA",
    "cdn-loop": "Fastly",
    "x-cloud-trace-context": "8314045b8ec3089dfe02a54d5c5af7c2/9187612188829829048;o=3",
    "cookie": "LIS=prod-znd-200923-mattmorg-p,prod-znd-200923-mattmorg-p--en,cs,en; KAVID=bfe95c5c-d828-456c-902a-ae4e6316cd3e; gae_b_id=!$tctxK2bi8sdbFw4jiEf0ZZzyMTmYBq79aKfEDk27oCM.~qhmcnx~1$a2FpZF80NTA5MTU4NTg1MzEyOTk5MTQ1ODY5NzEy",
    "x-appengine-region": "?",
    "x-appengine-country": "US",
    "x-appengine-citylatlong": "0.000000,0.000000",
    "x-appengine-city": "?",
    "traceparent": "00-8314045b8ec3089dfe02a54d5c5af7c2-7f80f49b914047b8-03",
    "x-appengine-timeout-ms": "599999",
    "x-appengine-https": "on",
    "x-appengine-user-ip": "185.31.18.35",
    "accept-encoding": "gzip",
    "x-appengine-request-log-id": "5f78430200ff08e72de9b56b650001737e6b68616e2d61636164656d79000172656e6465722d676174657761793a3230303932312d303930382d61386232386666393264633800010179",
    "x-appengine-default-version-hostname": "khan-academy.appspot.com"
}

Render Gateway Stack:

Error: Network error: /api/internal/graphql/footerDomainsQuery?fastly_cacheable=persist_until_publish&hash=646910179&variables=%7B%22curriculum%22%3A%22%22%7D&lang=en: Internal Server Error https://prod-znd-200826-michaelp-3.khanacademy.org/api/internal/graphql/footerDomainsQuery?fastly_cacheable=persist_until_publish&hash=646910179&variables=%7B%22curriculum%22%3A%22%22%7D&lang=en
    at new ApolloError (/workspace/node_modules/apollo-client/bundle.umd.js:59:32)
    at QueryManager. (/workspace/node_modules/apollo-client/bundle.umd.js:1183:49)
    at step (/workspace/node_modules/tslib/tslib.js:139:27)
    at Object.next (/workspace/node_modules/tslib/tslib.js:120:57)
    at /workspace/node_modules/tslib/tslib.js:113:75
    at new Promise ()
    at Object.__awaiter (/workspace/node_modules/tslib/tslib.js:109:16)
    at /workspace/node_modules/apollo-client/bundle.umd.js:1146:87
    at /workspace/node_modules/apollo-client/bundle.umd.js:1626:21
    at Array.forEach ()
```

**Comment by danielhollas** [comment]
@mpolyak actually, never mind. I'll work on this PR a little more, we can deploy later.

**Comment by danielhollas** [comment]
This needs more work, but I need to focus on other stuff first. I'll open a new PR when it's ready.

**Comment by danielhollas** [comment]
One more exercise for testing:
https://www.khanacademy.org/translations/edit/cs/math/7-trida/x32816229be4474b9:shodnost-a-podobnost/x32816229be4474b9:vlastnosti-a-definice-zobrazeni/e/find-measures-using-rigid-transformations/tree/upstream

**Pull request closed without merging**
